version: '2.4'

services:
  db:
    container_name: 'WHE_database'
    image: postgres:12
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=passw0rd
      - POSTGRES_DB=apidb
    ports:
      - '5432'
    volumes:
      - ./Database:/var/lib/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d apidb -U admin -h 0.0.0.0 -p 5432"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
     - private_network

  dokuwiki:
    image: 'docker.io/bitnami/dokuwiki:20200729-debian-10'
    restart: unless-stopped
    ports:
     - '8080:8080'
     - '8443:8443'
    volumes:
     - ./dokuwiki_data:/bitnami/dokuwiki
    networks:
     - private_network

networks:
  private_network:
    driver: bridge
