# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Thu, 04 Feb 2021 15:44:23 +0000
*	@ALL	1
reportstpl	@user	2
sidebar	@ALL	1
unapproved_reports	@user	1
unapproved_reports	@ALL	0
unapprovedreports:*	@user	8
unapprovedreports:*	@ALL	8
wiki:*	@ALL	8
