<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: luisa
 * Date: Tue, 16 Mar 2021 04:05:36 +0000
 */

$conf['title'] = 'WSE';
$conf['template'] = 'vector';
$conf['license'] = 'cc-by-sa';
$conf['recent'] = 5;
$conf['breadcrumbs'] = 0;
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'index,recent,revisions,register';
$conf['htmlok'] = 1;
$conf['target']['extern'] = '_blank';
$conf['target']['media'] = '_blank';
$conf['target']['windows'] = '_blank';
$conf['userewrite'] = '1';
$conf['plugin']['dropfiles']['insertFileLink'] = 1;
$conf['plugin']['tplmod']['sitetools'] = 'Media Manager';
$conf['tpl']['vector']['vector_sitenotice'] = 0;
