<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: luisa
 * Date: Tue, 23 Feb 2021 20:26:21 +0000
 */

$conf['title'] = 'WSE';
$conf['template'] = 'vector';
$conf['license'] = 'cc-by-sa';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['htmlok'] = 1;
$conf['target']['extern'] = '_blank';
$conf['target']['media'] = '_blank';
$conf['target']['windows'] = '_blank';
$conf['userewrite'] = '1';
