# users.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Userfile
#
# Auto-generated by install script
# Date: Thu, 04 Feb 2021 15:44:23 +0000
#
# Format:
# login:passwordhash:Real Name:email:groups,comma,separated

user:$2y$10$OBtLj1huPWA6BjkCRSBWxOPBDoRrXLF5dZaLT3fu9K1wBDf9O.UfW:FirstName LastName:user@example.com:admin,user
