# users.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Userfile
#
# Auto-generated by install script
# Date: Thu, 04 Feb 2021 15:44:23 +0000
#
# Format:
# login:passwordhash:Real Name:email:groups,comma,separated

luisa:$2y$10$wAkJ6XF9yMWqqNOZhVQtmuf7Lfsy61vMxL9qwRG8CDg.iqoyJ7NT6:Luísa Costa:lisacosta99@gmail.com:admin,user
user:$2y$10$bHKUvkXX6VqWvQx2E7mfkOjAwgFhaR2q4cyoIpXmnrN2.df3tKKrC:teste user:lisacosta99@gmail.com:admin,user
teste:$2y$10$KQUeCVzzX2VDhHkWql8YJuiGRVgx1xLbsgSrcCQ3qgUFoalyYX3Hy:teste:teste@teste.com:admin,user
